version: "2.0"

services:

  db:
    build:
      context: ..
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
        - no_proxy=${no_proxy}
    environment:
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_DB: ${PGSQL_DATABASE}
      # next environments is requirements for database dump
      BACKUP_TARGET: /tmp/backup
    volumes:
      - ./dump:/tmp/backup

  adminer:
    image: adminer
    ports:
      - 8080:8080